"use strict";
exports.__esModule = true;
var Account_1 = require("./Account");
var Department_1 = require("./Department");
var Possition_1 = require("./Possition");
var dep1 = new Department_1.Department(1, "Develop");
var dep2 = new Department_1.Department(2, "Sale");
var dep3 = new Department_1.Department(3, "Master");
console.log("In thông tin các phòng ban");
(0, Department_1.printInForDepartment)(dep1);
(0, Department_1.printInForDepartment)(dep2);
(0, Department_1.printInForDepartment)(dep3);
var pos1 = new Possition_1.Possition(1, "Dev");
var pos2 = new Possition_1.Possition(2, "Ok");
var pos3 = new Possition_1.Possition(3, "VTI");
console.log("In thông tin các khu vực");
(0, Possition_1.printInForPossition)(pos1);
(0, Possition_1.printInForPossition)(pos2);
(0, Possition_1.printInForPossition)(pos3);
var date = new Date("2021-09-26");
var acc1 = new Account_1.Account(1, "nnloc123@gmail.com", "loc", "nguyenloc", dep1, pos1, date);
var acc2 = new Account_1.Account(2, "ok@gmail.com", "ok", "ok ok", dep2, pos2, date);
console.log("In thông tin account");
(0, Account_1.printInforAccount)(acc1);
(0, Account_1.printInforAccount)(acc2);
